[package]
authors = ["Albert Hermida <albert@switchboard.xyz>"]
name = "Example"
version = "1.0.0"

[addresses]
example = "_"
std = "0x1"
switchboard = "0x4fc1809ffb3c5ada6b4e885d4dbdbeb70cbdd99cbc0c8485965d95c2eab90935"

[dev-addresses]
example = '0x55'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-framework"}
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-stdlib"}
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/move-stdlib"}
Switchboard = { git = "https://github.com/switchboard-xyz/aptos.git", rev = "main", subdir = "on_demand"}